---
- name: Deploy Jitsu Application with Docker Compose
  hosts: all
  become: true
  vars:
    ansible_ssh_private_key_file: "/home/mohsin/Desktop/devops/assignment/.vagrant/machines/jitsu/virtualbox/private_key"
    ansible_ssh_port: 2222

  tasks:
    - name: Install Docker and Docker Compose
      block:
        - name: Install required packages for Docker
          package:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg-agent
              - software-properties-common
            state: present
          when: ansible_distribution == 'Ubuntu'

        - name: Add Docker GPG key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
          when: ansible_distribution == 'Ubuntu'

        - name: Add Docker repository
          apt_repository:
            repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
          when: ansible_distribution == 'Ubuntu'

        - name: Install Docker and Docker Compose
          package:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-compose
            state: present
      tags:
        - docker

    - name: Create Docker Compose directory
      file:
        path: "/vagrant/docker"
        state: directory
      tags:
        - docker

    - name: Start Jitsu Docker Compose
      command: "docker-compose up -d"
      args:
        chdir: "/vagrant/docker"
      tags:
        - docker

    - name: Debug Information
      debug:
        var: inventory_hostname

