Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.define "jitsu"  
  config.vm.hostname = "jitsu"
  config.vm.network "forwarded_port", guest: 8000, host: 9000, host_ip: "127.0.0.1"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "main.yml"
  end
end

